version: "3.8"
services:
  nginx-proxy:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certificates:/etc/nginx/certificates

networks:
    network: 